version: "3.9"
services:
  web:
    build: ./app-server
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    expose:
      - 27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
 
  