version: '3.9'
services:
  web:
    build: ./app-server
    environment:
      - DEBUG=True 
    ports:
      - 80:3000
    volumes:
      - ./:/code
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
 
  