version: "3.9"
services:
  web:
    build:
      context: app-server
      dockerfile: Dockerfile.debug
    ports:
      - 9229:9229
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: